// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhTtGUE4Yk8GmAyscNh_A64H7mrL5nurQ',
    appId: '1:1061574387033:web:f3b37e12a58649259ed848',
    messagingSenderId: '1061574387033',
    projectId: 'redditflutter-ee2f0',
    authDomain: 'redditflutter-ee2f0.firebaseapp.com',
    storageBucket: 'redditflutter-ee2f0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHekxyEhZwBaPfD97uZPXYl18-bbgUuHY',
    appId: '1:1061574387033:android:2eb91a0d4e5975939ed848',
    messagingSenderId: '1061574387033',
    projectId: 'redditflutter-ee2f0',
    storageBucket: 'redditflutter-ee2f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLe13u9MyO661Pv1ToweKdszgKfJ_oQrs',
    appId: '1:1061574387033:ios:9aa596debc00ae839ed848',
    messagingSenderId: '1061574387033',
    projectId: 'redditflutter-ee2f0',
    storageBucket: 'redditflutter-ee2f0.appspot.com',
    iosBundleId: 'com.example.redditFlutter',
  );
}
